stages:
  data_ingestion:
    cmd: python src/ImageCaptioning/pipeline/stage_01_data_ingestion.py
    deps:
      - src/ImageCaptioning/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion

  data_transformation:
    cmd: python src/ImageCaptioning/pipeline/stage_02_data_transformation.py
    deps:
      - src/ImageCaptioning/pipeline/stage_02_data_transformation.py
      - artifacts/data_ingestion
    outs:
      - artifacts/data_transformation/vocab.pkl

  model_trainer:
    cmd: python src/ImageCaptioning/pipeline/stage_03_model_trainer.py
    deps:
      - src/ImageCaptioning/pipeline/stage_03_model_trainer.py
      - src/ImageCaptioning/components/model.py
      - src/ImageCaptioning/components/model_trainer.py
      - artifacts/data_transformation/vocab.pkl
      - artifacts/data_ingestion
    params:
      - embed_size
      - hidden_size
      - num_epochs
      - batch_size
      - learning_rate
    outs:
      - artifacts/model_trainer/model.pth

  model_evaluation:
    cmd: python src/ImageCaptioning/pipeline/stage_04_model_evaluation.py
    deps:
      - src/ImageCaptioning/pipeline/stage_04_model_evaluation.py
      - artifacts/model_trainer/model.pth
      - artifacts/data_transformation/vocab.pkl
      - artifacts/data_ingestion
    metrics:
      - artifacts/model_evaluation/metrics.json:
          cache: false
